spring:
  kafka:
    bootstrap-servers: localhost:9092
    replicationFactor: 1
    consumer:
      group-id: test-consumer-group
    auto:
      offset:
        reset: earliest

topicConfig:
  testTopic: kafka-spring-test-topic
  partitionCount: 1