application:
  api:
    version: v1

server:
  port: 8118

info:
  app:
    name: Kafka - spring workshop playground
    description: microservice playing around with kafka and spring
    version: 1.0
spring:
  application:
    name: Kafka-spring playground
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 5
      max-poll-interval-ms: 3000
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    listener:
      ack-mode: MANUAL_IMMEDIATE
    client-id: test-data-consumer
    replicationFactor: 1

topicConfig:
  testTopic: kafka-spring-test-topic
  partitionCount: 2

# Log config
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
